// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a particular location within a row or column band.
 */
export type BandLoc = number;