// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a row or column of blocks in a Sudoku grid.
 */
export type Band = number;