// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one of the 9 3x3 blocks in a Sudoku grid.
 *
 * Blocks are numbered in row-major order.
 */
export type Blk = number;