// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one of the mini-rows or -columns within a block.
 *
 * Block rows and columns are ordered in the same directions as full rows and columns.
 */
export type BlkLine = number;