// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one of the 9 columns in a Sudoku grid.
 *
 * Columns are numbered left to right.
 */
export type Col = number;