// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fact } from "./Fact";

export type DeduceResult = { facts: Array<Fact>, timedOut: boolean, };