// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Loc } from "./Loc";
import type { Num } from "./Num";

export type ErroneousAssignmentProductivity = { loc: Loc, num: Num, productivity: number, };