// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Loc } from "./Loc";
import type { LocSet } from "../../../../www/src/facts/LocSet";
import type { Num } from "../../../../www/src/facts/Num";
import type { NumSet } from "../../../../www/src/facts/NumSet";
import type { Unit } from "./Unit";

export type Fact = { "type": "SingleLoc", num: Num, unit: Unit, loc: Loc, } | { "type": "SingleNum", loc: Loc, num: Num, } | { "type": "SpeculativeAssignment", loc: Loc, num: Num, } | { "type": "NoLoc", num: Num, unit: Unit, } | { "type": "NoNum", loc: Loc, } | { "type": "Conflict", num: Num, unit: Unit, locs: LocSet, } | { "type": "Overlap", num: Num, unit: Unit, cross_unit: Unit, } | { "type": "Subset", nums: NumSet, unit: Unit, locs: LocSet, cross_unit: Unit | null, is_naked: boolean, } | { "type": "Implication", antecedents: Array<Fact>, consequent: Fact, };