// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one of the 81 locations in a Sudoku grid.
 *
 * Sudokus are represented as length-81 arrays in row-major order.
 * `Loc(0)` is the top left square of the grid, and `Loc(80)` is the
 * bottom right.
 */
export type Loc = number;