// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one of the 9 numerals that can can occupy a location of a
 * Sudoku grid.
 */
export type Num = number;