// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one of the 9 rows in a Sudoku grid.
 *
 * Rows are numbered top to bottom.
 */
export type Row = number;