// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fact } from "./Fact";
import type { SearchProgress } from "./SearchProgress";

export type SearchDisproofsResult = { disproofs: Array<Fact>, progress: SearchProgress, };