// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one of the 27 "units" (row/col/block) of a Sudoku grid.
 *
 * The units of a Sudoku (not to be confused with Rust's unit type) are
 * all the subregions of the grid that must contain all 9 numerals in a
 * valid solution.
 */
export type UnitId = number;