// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Blk } from "./Blk";
import type { Col } from "./Col";
import type { Row } from "./Row";

export type Unit = { "type": "Blk", "id": Blk } | { "type": "Row", "id": Row } | { "type": "Col", "id": Col };