arrowParens: "avoid"
bracketSpacing: false
endOfLine: "lf"
experimentalTernaries: true
htmlWhitespaceSensitivity: "css"
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 80
proseWrap: "preserve"
quoteProps: "as-needed"
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "all"
useTabs: false
vueIndentScriptAndStyle: false
plugins:
  - "prettier-plugin-organize-imports"

